# Setup
title:               doctorX
tagline:             'self medicating security issues'
description:         'Principal Engg @ Zillow. Opinions are my own'                     
url:                 #"https://kidd0123.github.io" 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Vamsi NC
  url:               https://linkedin.com/in/ncvamsi
  email:             nc.vamsi@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
