# Setup
title:               doctorX
tagline:             'self medicating security issues'
description:         ''
url:                 #"https://kidd0123.github.io" 
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name: Vamsi NC
  github: kidd0123
  email:  nc.vamsi@gmail.com
  bugcrowd: kidd0123
  libravatar_md5: 3bb1cf1cb34b1dc376f50cb44b7dccdc
  linkedin: ncvamsi

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
